#@PydevCodeAnalysisIgnore
# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _mdAddrPythonWrapper
import new
new_instancemethod = new.instancemethod
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

class mdAddr:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdAddr, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdAddr, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdAddr_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdAddr_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdAddr_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdAddr_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdAddr_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdAddr_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdAddr_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdAddr_Local
    Remote = _mdAddrPythonWrapper.mdAddr_Remote
    Auto = _mdAddrPythonWrapper.mdAddr_Auto
    On = _mdAddrPythonWrapper.mdAddr_On
    Off = _mdAddrPythonWrapper.mdAddr_Off
    def __init__(self, *args): 
        this = apply(_mdAddrPythonWrapper.new_mdAddr, args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdAddr
    __del__ = lambda self : None;
    def Initialize(*args): return apply(_mdAddrPythonWrapper.mdAddr_Initialize, args)
    def InitializeDataFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_InitializeDataFiles, args)
    def GetInitializeErrorString(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetInitializeErrorString, args)
    def SetLicenseString(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetLicenseString, args)
    def GetBuildNumber(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetBuildNumber, args)
    def GetDatabaseDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDatabaseDate, args)
    def GetExpirationDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetExpirationDate, args)
    def GetCanadianDatabaseDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCanadianDatabaseDate, args)
    def GetCanadianExpirationDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCanadianExpirationDate, args)
    def SetPathToUSFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToUSFiles, args)
    def SetPathToCanadaFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToCanadaFiles, args)
    def SetPathToDPVDataFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToDPVDataFiles, args)
    def SetPathToLACSLinkDataFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToLACSLinkDataFiles, args)
    def SetPathToSuiteLinkDataFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToSuiteLinkDataFiles, args)
    def SetPathToSuiteFinderDataFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToSuiteFinderDataFiles, args)
    def SetPathToRBDIFiles(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPathToRBDIFiles, args)
    def GetRBDIDatabaseDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetRBDIDatabaseDate, args)
    def ClearProperties(*args): return apply(_mdAddrPythonWrapper.mdAddr_ClearProperties, args)
    def ResetDPV(*args): return apply(_mdAddrPythonWrapper.mdAddr_ResetDPV, args)
    def SetCASSEnable(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetCASSEnable, args)
    def SetUseUSPSPreferredCityNames(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetUseUSPSPreferredCityNames, args)
    def SetDiacritics(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetDiacritics, args)
    def GetStatusCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetStatusCode, args)
    def GetErrorCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetErrorCode, args)
    def GetErrorString(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetErrorString, args)
    def GetResults(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetResults, args)
    def SetPS3553_B1_ProcessorName(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_B1_ProcessorName, args)
    def SetPS3553_B4_ListName(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_B4_ListName, args)
    def SetPS3553_D3_Name(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Name, args)
    def SetPS3553_D3_Company(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Company, args)
    def SetPS3553_D3_Address(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_Address, args)
    def SetPS3553_D3_City(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_City, args)
    def SetPS3553_D3_State(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_State, args)
    def SetPS3553_D3_ZIP(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPS3553_D3_ZIP, args)
    def GetFormPS3553(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetFormPS3553, args)
    def SaveFormPS3553(*args): return apply(_mdAddrPythonWrapper.mdAddr_SaveFormPS3553, args)
    def ResetFormPS3553(*args): return apply(_mdAddrPythonWrapper.mdAddr_ResetFormPS3553, args)
    def GetFormSOA(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetFormSOA, args)
    def SaveFormSOA(*args): return apply(_mdAddrPythonWrapper.mdAddr_SaveFormSOA, args)
    def ResetFormSOA(*args): return apply(_mdAddrPythonWrapper.mdAddr_ResetFormSOA, args)
    def SetSOACustomerInfo(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetSOACustomerInfo, args)
    def SetSOACPCNumber(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetSOACPCNumber, args)
    def GetSOACustomerInfo(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOACustomerInfo, args)
    def GetSOACPCNumber(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOACPCNumber, args)
    def GetSOATotalRecords(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOATotalRecords, args)
    def GetSOAAAPercentage(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOAAAPercentage, args)
    def GetSOAAAExpiryDate(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOAAAExpiryDate, args)
    def GetSOASoftwareInfo(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOASoftwareInfo, args)
    def GetSOAErrorString(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSOAErrorString, args)
    def SetCompany(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetCompany, args)
    def SetLastName(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetLastName, args)
    def SetAddress(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetAddress, args)
    def SetAddress2(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetAddress2, args)
    def SetLastLine(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetLastLine, args)
    def SetSuite(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetSuite, args)
    def SetCity(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetCity, args)
    def SetState(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetState, args)
    def SetZip(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetZip, args)
    def SetPlus4(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetPlus4, args)
    def SetUrbanization(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetUrbanization, args)
    def SetParsedAddressRange(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedAddressRange, args)
    def SetParsedPreDirection(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedPreDirection, args)
    def SetParsedStreetName(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedStreetName, args)
    def SetParsedSuffix(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedSuffix, args)
    def SetParsedPostDirection(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedPostDirection, args)
    def SetParsedSuiteName(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedSuiteName, args)
    def SetParsedSuiteRange(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetParsedSuiteRange, args)
    def SetCountryCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetCountryCode, args)
    def VerifyAddress(*args): return apply(_mdAddrPythonWrapper.mdAddr_VerifyAddress, args)
    def GetCompany(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCompany, args)
    def GetLastName(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetLastName, args)
    def GetAddress(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetAddress, args)
    def GetAddress2(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetAddress2, args)
    def GetSuite(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSuite, args)
    def GetCity(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCity, args)
    def GetCityAbbreviation(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCityAbbreviation, args)
    def GetState(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetState, args)
    def GetZip(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetZip, args)
    def GetPlus4(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPlus4, args)
    def GetCarrierRoute(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCarrierRoute, args)
    def GetDeliveryPointCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDeliveryPointCode, args)
    def GetDeliveryPointCheckDigit(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDeliveryPointCheckDigit, args)
    def GetCountyFips(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCountyFips, args)
    def GetCountyName(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCountyName, args)
    def GetAddressTypeCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetAddressTypeCode, args)
    def GetAddressTypeString(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetAddressTypeString, args)
    def GetUrbanization(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetUrbanization, args)
    def GetCongressionalDistrict(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCongressionalDistrict, args)
    def GetLACS(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetLACS, args)
    def GetLACSLinkIndicator(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetLACSLinkIndicator, args)
    def GetPrivateMailbox(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPrivateMailbox, args)
    def GetTimeZoneCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetTimeZoneCode, args)
    def GetTimeZone(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetTimeZone, args)
    def GetMsa(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetMsa, args)
    def GetPmsa(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPmsa, args)
    def GetDefaultFlagIndicator(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDefaultFlagIndicator, args)
    def GetSuiteStatus(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSuiteStatus, args)
    def GetEWSFlag(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetEWSFlag, args)
    def GetCMRA(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCMRA, args)
    def GetDsfNoStats(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDsfNoStats, args)
    def GetDsfVacant(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDsfVacant, args)
    def GetCountryCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetCountryCode, args)
    def GetZipType(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetZipType, args)
    def GetFalseTable(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetFalseTable, args)
    def GetDPVFootnotes(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetDPVFootnotes, args)
    def GetLACSLinkReturnCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetLACSLinkReturnCode, args)
    def GetSuiteLinkReturnCode(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetSuiteLinkReturnCode, args)
    def GetRBDI(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetRBDI, args)
    def GetELotNumber(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetELotNumber, args)
    def GetELotOrder(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetELotOrder, args)
    def FindSuggestion(*args): return apply(_mdAddrPythonWrapper.mdAddr_FindSuggestion, args)
    def FindSuggestionNext(*args): return apply(_mdAddrPythonWrapper.mdAddr_FindSuggestionNext, args)
    def GetPS3553_B6_TotalRecords(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_B6_TotalRecords, args)
    def GetPS3553_C1a_ZIP4Coded(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_C1a_ZIP4Coded, args)
    def GetPS3553_C1c_DPBCAssigned(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_C1c_DPBCAssigned, args)
    def GetPS3553_C1d_FiveDigitCoded(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_C1d_FiveDigitCoded, args)
    def GetPS3553_C1e_CRRTCoded(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_C1e_CRRTCoded, args)
    def GetPS3553_C1f_eLOTAssigned(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_C1f_eLOTAssigned, args)
    def GetPS3553_E_HighRiseDefault(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_HighRiseDefault, args)
    def GetPS3553_E_HighRiseExact(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_HighRiseExact, args)
    def GetPS3553_E_RuralRouteDefault(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_RuralRouteDefault, args)
    def GetPS3553_E_RuralRouteExact(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_RuralRouteExact, args)
    def GetPS3553_E_LACSCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_LACSCount, args)
    def GetPS3553_E_EWSCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_EWSCount, args)
    def GetPS3553_E_DPVCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_E_DPVCount, args)
    def GetPS3553_X_POBoxCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_POBoxCount, args)
    def GetPS3553_X_HCExactCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_HCExactCount, args)
    def GetPS3553_X_FirmCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_FirmCount, args)
    def GetPS3553_X_GenDeliveryCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_GenDeliveryCount, args)
    def GetPS3553_X_MilitaryZipCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_MilitaryZipCount, args)
    def GetPS3553_X_NonDeliveryCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_NonDeliveryCount, args)
    def GetPS3553_X_StreetCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_StreetCount, args)
    def GetPS3553_X_HCDefaultCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_HCDefaultCount, args)
    def GetPS3553_X_OtherCount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_OtherCount, args)
    def GetPS3553_X_LacsLinkCodeACount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCodeACount, args)
    def GetPS3553_X_LacsLinkCode00Count(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode00Count, args)
    def GetPS3553_X_LacsLinkCode14Count(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode14Count, args)
    def GetPS3553_X_LacsLinkCode92Count(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode92Count, args)
    def GetPS3553_X_LacsLinkCode09Count(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_LacsLinkCode09Count, args)
    def GetPS3553_X_SuiteLinkCodeACount(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_SuiteLinkCodeACount, args)
    def GetPS3553_X_SuiteLinkCode00Count(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetPS3553_X_SuiteLinkCode00Count, args)
    def GetParsedAddressRange(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedAddressRange, args)
    def GetParsedPreDirection(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedPreDirection, args)
    def GetParsedStreetName(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedStreetName, args)
    def GetParsedSuffix(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedSuffix, args)
    def GetParsedPostDirection(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedPostDirection, args)
    def GetParsedSuiteName(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedSuiteName, args)
    def GetParsedSuiteRange(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedSuiteRange, args)
    def GetParsedPrivateMailboxName(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedPrivateMailboxName, args)
    def GetParsedPrivateMailboxNumber(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedPrivateMailboxNumber, args)
    def GetParsedGarbage(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetParsedGarbage, args)
    def SetReserved(*args): return apply(_mdAddrPythonWrapper.mdAddr_SetReserved, args)
    def GetReserved(*args): return apply(_mdAddrPythonWrapper.mdAddr_GetReserved, args)
mdAddr_swigregister = _mdAddrPythonWrapper.mdAddr_swigregister
mdAddr_swigregister(mdAddr)

class mdParse:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdParse, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdParse, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdParse_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdParse_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdParse_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdParse_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdParse_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdParse_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdParse_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdParse_Local
    Remote = _mdAddrPythonWrapper.mdParse_Remote
    Auto = _mdAddrPythonWrapper.mdParse_Auto
    On = _mdAddrPythonWrapper.mdParse_On
    Off = _mdAddrPythonWrapper.mdParse_Off
    def __init__(self, *args): 
        this = apply(_mdAddrPythonWrapper.new_mdParse, args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdParse
    __del__ = lambda self : None;
    def Initialize(*args): return apply(_mdAddrPythonWrapper.mdParse_Initialize, args)
    def GetBuildNumber(*args): return apply(_mdAddrPythonWrapper.mdParse_GetBuildNumber, args)
    def Parse(*args): return apply(_mdAddrPythonWrapper.mdParse_Parse, args)
    def ParseNext(*args): return apply(_mdAddrPythonWrapper.mdParse_ParseNext, args)
    def LastLineParse(*args): return apply(_mdAddrPythonWrapper.mdParse_LastLineParse, args)
    def GetZip(*args): return apply(_mdAddrPythonWrapper.mdParse_GetZip, args)
    def GetPlus4(*args): return apply(_mdAddrPythonWrapper.mdParse_GetPlus4, args)
    def GetCity(*args): return apply(_mdAddrPythonWrapper.mdParse_GetCity, args)
    def GetState(*args): return apply(_mdAddrPythonWrapper.mdParse_GetState, args)
    def GetStreetName(*args): return apply(_mdAddrPythonWrapper.mdParse_GetStreetName, args)
    def GetRange(*args): return apply(_mdAddrPythonWrapper.mdParse_GetRange, args)
    def GetPreDirection(*args): return apply(_mdAddrPythonWrapper.mdParse_GetPreDirection, args)
    def GetPostDirection(*args): return apply(_mdAddrPythonWrapper.mdParse_GetPostDirection, args)
    def GetSuffix(*args): return apply(_mdAddrPythonWrapper.mdParse_GetSuffix, args)
    def GetSuiteName(*args): return apply(_mdAddrPythonWrapper.mdParse_GetSuiteName, args)
    def GetSuiteNumber(*args): return apply(_mdAddrPythonWrapper.mdParse_GetSuiteNumber, args)
    def GetPrivateMailboxNumber(*args): return apply(_mdAddrPythonWrapper.mdParse_GetPrivateMailboxNumber, args)
    def GetPrivateMailboxName(*args): return apply(_mdAddrPythonWrapper.mdParse_GetPrivateMailboxName, args)
    def GetGarbage(*args): return apply(_mdAddrPythonWrapper.mdParse_GetGarbage, args)
    def ParseRule(*args): return apply(_mdAddrPythonWrapper.mdParse_ParseRule, args)
mdParse_swigregister = _mdAddrPythonWrapper.mdParse_swigregister
mdParse_swigregister(mdParse)

class mdStreet:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdStreet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdStreet, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdStreet_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdStreet_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdStreet_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdStreet_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdStreet_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdStreet_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdStreet_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdStreet_Local
    Remote = _mdAddrPythonWrapper.mdStreet_Remote
    Auto = _mdAddrPythonWrapper.mdStreet_Auto
    On = _mdAddrPythonWrapper.mdStreet_On
    Off = _mdAddrPythonWrapper.mdStreet_Off
    def __init__(self, *args): 
        this = apply(_mdAddrPythonWrapper.new_mdStreet, args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdStreet
    __del__ = lambda self : None;
    def Initialize(*args): return apply(_mdAddrPythonWrapper.mdStreet_Initialize, args)
    def GetInitializeErrorString(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetInitializeErrorString, args)
    def GetDatabaseDate(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetDatabaseDate, args)
    def GetBuildNumber(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetBuildNumber, args)
    def SetLicenseString(*args): return apply(_mdAddrPythonWrapper.mdStreet_SetLicenseString, args)
    def FindStreet(*args): return apply(_mdAddrPythonWrapper.mdStreet_FindStreet, args)
    def FindStreetNext(*args): return apply(_mdAddrPythonWrapper.mdStreet_FindStreetNext, args)
    def IsAddressInRange(*args): return apply(_mdAddrPythonWrapper.mdStreet_IsAddressInRange, args)
    def IsAddressInRange2(*args): return apply(_mdAddrPythonWrapper.mdStreet_IsAddressInRange2, args)
    def GetBaseAlternateIndicator(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetBaseAlternateIndicator, args)
    def GetLACSIndicator(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetLACSIndicator, args)
    def GetUrbanizationCode(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetUrbanizationCode, args)
    def GetUrbanizationName(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetUrbanizationName, args)
    def GetLastLineNumber(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetLastLineNumber, args)
    def GetAddressType(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetAddressType, args)
    def GetCongressionalDistrict(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetCongressionalDistrict, args)
    def GetCountyFips(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetCountyFips, args)
    def GetCompany(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetCompany, args)
    def GetCarrierRoute(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetCarrierRoute, args)
    def GetZip(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetZip, args)
    def GetPlus4High(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPlus4High, args)
    def GetPlus4Low(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPlus4Low, args)
    def GetSuiteRangeOddEven(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetSuiteRangeOddEven, args)
    def GetSuiteRangeHigh(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetSuiteRangeHigh, args)
    def GetSuiteRangeLow(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetSuiteRangeLow, args)
    def GetSuiteName(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetSuiteName, args)
    def GetPostDirection(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPostDirection, args)
    def GetSuffix(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetSuffix, args)
    def GetStreetName(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetStreetName, args)
    def GetPreDirection(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPreDirection, args)
    def GetPrimaryRangeOddEven(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPrimaryRangeOddEven, args)
    def GetPrimaryRangeHigh(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPrimaryRangeHigh, args)
    def GetPrimaryRangeLow(*args): return apply(_mdAddrPythonWrapper.mdStreet_GetPrimaryRangeLow, args)
mdStreet_swigregister = _mdAddrPythonWrapper.mdStreet_swigregister
mdStreet_swigregister(mdStreet)

class mdZip:
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, mdZip, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, mdZip, name)
    __repr__ = _swig_repr
    ErrorNone = _mdAddrPythonWrapper.mdZip_ErrorNone
    ErrorOther = _mdAddrPythonWrapper.mdZip_ErrorOther
    ErrorOutOfMemory = _mdAddrPythonWrapper.mdZip_ErrorOutOfMemory
    ErrorRequiredFileNotFound = _mdAddrPythonWrapper.mdZip_ErrorRequiredFileNotFound
    ErrorFoundOldFile = _mdAddrPythonWrapper.mdZip_ErrorFoundOldFile
    ErrorDatabaseExpired = _mdAddrPythonWrapper.mdZip_ErrorDatabaseExpired
    ErrorLicenseExpired = _mdAddrPythonWrapper.mdZip_ErrorLicenseExpired
    Local = _mdAddrPythonWrapper.mdZip_Local
    Remote = _mdAddrPythonWrapper.mdZip_Remote
    Auto = _mdAddrPythonWrapper.mdZip_Auto
    On = _mdAddrPythonWrapper.mdZip_On
    Off = _mdAddrPythonWrapper.mdZip_Off
    def __init__(self, *args): 
        this = apply(_mdAddrPythonWrapper.new_mdZip, args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mdAddrPythonWrapper.delete_mdZip
    __del__ = lambda self : None;
    def Initialize(*args): return apply(_mdAddrPythonWrapper.mdZip_Initialize, args)
    def GetInitializeErrorString(*args): return apply(_mdAddrPythonWrapper.mdZip_GetInitializeErrorString, args)
    def GetDatabaseDate(*args): return apply(_mdAddrPythonWrapper.mdZip_GetDatabaseDate, args)
    def GetBuildNumber(*args): return apply(_mdAddrPythonWrapper.mdZip_GetBuildNumber, args)
    def SetLicenseString(*args): return apply(_mdAddrPythonWrapper.mdZip_SetLicenseString, args)
    def FindZip(*args): return apply(_mdAddrPythonWrapper.mdZip_FindZip, args)
    def FindZipNext(*args): return apply(_mdAddrPythonWrapper.mdZip_FindZipNext, args)
    def FindZipInCity(*args): return apply(_mdAddrPythonWrapper.mdZip_FindZipInCity, args)
    def FindZipInCityNext(*args): return apply(_mdAddrPythonWrapper.mdZip_FindZipInCityNext, args)
    def FindCityInState(*args): return apply(_mdAddrPythonWrapper.mdZip_FindCityInState, args)
    def FindCityInStateNext(*args): return apply(_mdAddrPythonWrapper.mdZip_FindCityInStateNext, args)
    def ComputeDistance(*args): return apply(_mdAddrPythonWrapper.mdZip_ComputeDistance, args)
    def ComputeBearing(*args): return apply(_mdAddrPythonWrapper.mdZip_ComputeBearing, args)
    def GetCountyNameFromFips(*args): return apply(_mdAddrPythonWrapper.mdZip_GetCountyNameFromFips, args)
    def GetSCFArea(*args): return apply(_mdAddrPythonWrapper.mdZip_GetSCFArea, args)
    def GetZip(*args): return apply(_mdAddrPythonWrapper.mdZip_GetZip, args)
    def GetCity(*args): return apply(_mdAddrPythonWrapper.mdZip_GetCity, args)
    def GetCityAbbreviation(*args): return apply(_mdAddrPythonWrapper.mdZip_GetCityAbbreviation, args)
    def GetState(*args): return apply(_mdAddrPythonWrapper.mdZip_GetState, args)
    def GetZipType(*args): return apply(_mdAddrPythonWrapper.mdZip_GetZipType, args)
    def GetCountyName(*args): return apply(_mdAddrPythonWrapper.mdZip_GetCountyName, args)
    def GetCountyFips(*args): return apply(_mdAddrPythonWrapper.mdZip_GetCountyFips, args)
    def GetAreaCode(*args): return apply(_mdAddrPythonWrapper.mdZip_GetAreaCode, args)
    def GetLongitude(*args): return apply(_mdAddrPythonWrapper.mdZip_GetLongitude, args)
    def GetLatitude(*args): return apply(_mdAddrPythonWrapper.mdZip_GetLatitude, args)
    def GetTimeZone(*args): return apply(_mdAddrPythonWrapper.mdZip_GetTimeZone, args)
    def GetTimeZoneCode(*args): return apply(_mdAddrPythonWrapper.mdZip_GetTimeZoneCode, args)
    def GetMsa(*args): return apply(_mdAddrPythonWrapper.mdZip_GetMsa, args)
    def GetPmsa(*args): return apply(_mdAddrPythonWrapper.mdZip_GetPmsa, args)
    def GetFacilityCode(*args): return apply(_mdAddrPythonWrapper.mdZip_GetFacilityCode, args)
    def GetLastLineIndicator(*args): return apply(_mdAddrPythonWrapper.mdZip_GetLastLineIndicator, args)
    def GetLastLineNumber(*args): return apply(_mdAddrPythonWrapper.mdZip_GetLastLineNumber, args)
    def GetPreferredLastLineNumber(*args): return apply(_mdAddrPythonWrapper.mdZip_GetPreferredLastLineNumber, args)
    def GetAutomation(*args): return apply(_mdAddrPythonWrapper.mdZip_GetAutomation, args)
    def GetFinanceNumber(*args): return apply(_mdAddrPythonWrapper.mdZip_GetFinanceNumber, args)
mdZip_swigregister = _mdAddrPythonWrapper.mdZip_swigregister
mdZip_swigregister(mdZip)



