from project.rent.models import BaseRentalPlan


class RentalPlansDataMixin(object):
    _plans_data = {
        BaseRentalPlan.PlanA: {
            "plan": BaseRentalPlan.PlanA,
            "title": "Monthly 1 Game Plan",
            "terms": "1 GAME out at-a-time (Limited)",
            "slug": "old_limited",
            "out_per_month": 2,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 1,
        },
        BaseRentalPlan.PlanB: {
            "plan": BaseRentalPlan.PlanB,
            "title": "Monthly 2 Game Plan",
            "terms": "2 GAMES out at-a-time (Unlimited)",
            "slug": "old_unlimited",
            "out_per_month": None,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 1,
        },
        BaseRentalPlan.PlanC: {
            "plan": BaseRentalPlan.PlanC,
            "title": "Monthly 3 Game Plan",
            "terms": "3 GAMES out-at-time (Unlimited)",
            "slug": "unlimited3",
            "out_per_month": None,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 1,
        },
        BaseRentalPlan.PlanD: {
            "plan": BaseRentalPlan.PlanD,
            "title": "3 Months 2 Game Plan",
            "terms": "2 GAMES out at-a-time (Unlimited)",
            "slug": "unlimited_prepaid3",
            "out_per_month": None,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 3,
        },
        BaseRentalPlan.PlanE: {
            "plan": BaseRentalPlan.PlanE,
            "title": "6 Months 2 Game Plan",
            "terms": "2 GAMES out at-a-time (Unlimited)",
            "slug": "unlimited_prepaid6",
            "out_per_month": None,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 6,
        },
        BaseRentalPlan.PlanF: {
            "plan": BaseRentalPlan.PlanF,
            "title": "Monthly 1 Game Plan",
            "terms": "1 GAME out at-a-time (Limited)",
            "slug": "limited",
            "out_per_month": 2,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 1,
        },
        BaseRentalPlan.PlanG: {
            "plan": BaseRentalPlan.PlanG,
            "title": "Monthly 2 Game Plan",
            "terms": "2 GAMES out at-a-time (Unlimited)",
            "slug": "unlimited",
            "out_per_month": None,
            "next_plan": None,
            "first_payment_type": "AUTH_CAPTURE",
            "period_in_months": 1,
        },
        BaseRentalPlan.PlanH: {
            "plan": BaseRentalPlan.PlanH,
            "title": "Monthly 2 Game Plan",
            "terms": "2 GAMES out at-a-time (Unlimited)",
            "slug": "free_trial",
            "out_per_month": None,
            "next_plan": BaseRentalPlan.PlanB,
            "first_payment_type": "AUTH_ONLY",
            "period_in_months": 1,
        },
    }
